# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu/precise64"
#  config.vm.hostname = 'web'
#  config.vm.box_url = "ubuntu/precise64"
#
#  config.vm.network :private_network, ip: "192.168.56.101"
#
#  config.vm.provider :virtualbox do |v|
#    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#    v.customize ["modifyvm", :id, "--memory", 512]
#    v.customize ["modifyvm", :id, "--name", "web"]
#  end
#end



Vagrant.configure("2") do |config|

  config.vm.define "vc0" do |vc0|
    vc0.vm.box = "centos/7"
    vc0.vm.hostname = 'vc0'
    vc0.vm.box_url = "centos/7"

    vc0.vm.network :public_network, ip: "192.168.1.130", bridge: "wlp2s0"

    vc0.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 7168]
      v.customize ["modifyvm", :id, "--name", "vc0"]
      v.customize ["modifyvm", :id, "--cpus", "4"]
    end
  end

end
