Vagrant.configure("2") do |config|

  config.vm.define "zoo0" do |zoo|
    zoo.vm.box = "centos/7"
    zoo.vm.hostname = 'zoo0'
    zoo.vm.box_url = "centos/7"

    zoo.vm.network :private_network, ip: "192.168.2.140"
    
    zoo.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 3072]
      v.customize ["modifyvm", :id, "--name", "zoo0"]
      v.customize ["modifyvm", :id, "--cpus", "4"]
    end
  end
end


